### ISSUE TITLE
question about testing data

### ISSUE THREAD

**Issue by RazHoshia** [nicomignoni/tab2img#1]
Hi,
Maybe I misunderstood, but if I have testing data without a label, how can I transfer it to an image and put it in the model I trained?

**Comment by nicomignoni** [comment]
@RazHoshia no, you're right, i forgot about the testing data. I fixed it adding a `fit` method that saves the mapping from the tabular data to the images tensor. Then, you can use the `transform` method to transform your (unlabelled) data. 
Thanks for make me notice it, btw

**Comment by RazHoshia** [comment]
Thank You for your help and also for sharing the code with the community!
